services:
  postgres:
    image: postgres:15
    container_name: mojo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mojo_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

